# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
from group import Group

class TestTestaddgroup():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_add_group(self):
    self.open_home_page()
    self.login(username="admin", password="secret")
    self.open_groups_page()
    self.create_group(Group(name="444", header="444", footer="444"))
    self.return_to_group_page()
    self.logout()

  def test_add_empty_group(self):
    self.open_home_page()
    self.login(username="admin", password="secret")
    self.open_groups_page()
    self.create_group(Group(name="", header="", footer=""))
    self.return_to_group_page()
    self.logout()

  def open_home_page(self):  # открываем главную страницу
    self.driver.get("http://localhost/addressbook/")

  def login(self, username, password):  # логинимся
    self.driver.find_element(By.NAME, "user").send_keys(username)
    self.driver.find_element(By.NAME, "pass").click()
    self.driver.find_element(By.NAME, "pass").send_keys(password)
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(7)").click()

  def open_groups_page(self): # переходим на страницу "groups"
    self.driver.find_element(By.LINK_TEXT, "groups").click()

  def create_group(self, group): # создаем новую группу, заполняем поля, сохраняем
    self.driver.find_element(By.CSS_SELECTOR, "[name = ""new""]").click()
    self.driver.find_element(By.NAME, "group_name").click()
    self.driver.find_element(By.NAME, "group_name").send_keys(group.name)
    self.driver.find_element(By.NAME, "group_header").click()
    self.driver.find_element(By.NAME, "group_header").send_keys(group.header)
    self.driver.find_element(By.NAME, "group_footer").click()
    self.driver.find_element(By.NAME, "group_footer").send_keys(group.footer)
    self.driver.find_element(By.NAME, "submit").click()

  def return_to_group_page(self): # возвращаемся на страницу "groups"
    self.driver.find_element(By.LINK_TEXT, "group page").click()

  def logout(self): # разлогиниваемся
    self.driver.find_element(By.LINK_TEXT, "Logout").click()










